name: Telegram Forwarder Engine

on:
  workflow_dispatch:
    inputs:
      legenda_busca:
        description: 'Legenda exata a buscar'
        required: false
        default: ''
        type: string

jobs:
  processar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install pyrogram tgcrypto

      - name: Indexar Legendas do Canal
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          CANAL_ORIGEM: ${{ secrets.CANAL_ORIGEM }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
        run: python atualizar_legendas.py

      - name: Commit e Push do legendas.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add legendas.json
          git commit -m "Atualizando lista de legendas [skip ci]" || exit 0
          git push

      - name: Executar Envio de Midia
        if: ${{ github.event.inputs.legenda_busca != '' }}
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          CANAL_ORIGEM: ${{ secrets.CANAL_ORIGEM }}
          CANAL_DESTINO: ${{ secrets.CANAL_DESTINO }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          LEGENDA_BUSCA: ${{ github.event.inputs.legenda_busca }}
        run: python busca_e_envia.py
